# Generated by Django 3.0.5 on 2021-02-27 17:43

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('points', models.CharField(max_length=1000, verbose_name='Json of points')),
            ],
        ),
    ]
